import { Card, CardContent, CardHeader, CardTitle } from "@ru/ui";
import {
  BookOpen,
  Users,
  Calendar,
  CreditCard,
  Ticket,
  ShoppingBag,
  MessageSquare,
  Settings,
  Webhook,
  LayoutDashboard,
  UserCheck,
  RefreshCw,
  FlaskConical,
  ShieldCheck,
  ExternalLink,
  Globe,
  Smartphone,
  CheckCircle2,
} from "lucide-react";

const sections = [
  {
    title: "Dashboard",
    icon: LayoutDashboard,
    href: "/admin",
    description:
      "Your command center. Shows total users, monthly revenue, active memberships, upcoming sessions, revenue by plan, and recent orders. All data is real-time from the database.",
    tips: [
      "Check this daily to monitor new sign-ups and revenue trends",
      "Revenue comparison shows month-over-month growth percentage",
      "Recent orders table shows the last 10 paid orders",
    ],
  },
  {
    title: "Users",
    icon: Users,
    href: "/admin/users",
    description:
      "View and manage all registered users. See their email, name, phone, role, membership status, and when they joined. Click any user to see full details.",
    tips: [
      "Use the user detail page to view their bookings, memberships, and orders",
      "Users are synced from Clerk authentication — they appear here after sign-up",
      "Roles: USER (default), COACH, ADMIN",
    ],
  },
  {
    title: "Coaches",
    icon: UserCheck,
    href: "/admin/coaches",
    description:
      "Manage coach profiles. Coaches can be assigned to batches and sessions. Each coach has a name, bio, specialties, and an optional profile image.",
    tips: [
      "Create a coach profile before assigning them to batches",
      "Coach specialties help users understand what each coach offers",
      "A coach must also have a User account with role COACH",
    ],
  },
  {
    title: "Batches",
    icon: Calendar,
    href: "/admin/batches",
    description:
      "Batches are recurring class schedules. Each batch belongs to a product (Face Yoga, Pranayama, or Bundle) and defines which days of the week, what time, and which coach runs the sessions.",
    tips: [
      "Set the days of week, start time, and timezone for each batch",
      "Sessions are auto-generated from batch schedules via the cron job",
      "You can set modalities per day (e.g., Monday = Jawline, Tuesday = Eyes)",
      "Deactivating a batch stops future session generation",
    ],
  },
  {
    title: "Sessions",
    icon: BookOpen,
    href: "/admin/sessions",
    description:
      "Individual class sessions generated from batches. Each session has a date, time, Google Meet link, coach assignment, and recording status.",
    tips: [
      "Sessions are auto-generated by the cron job from active batches",
      "Click 'Generate Meet' to create a Google Meet link for a session",
      "Recordings are auto-fetched after sessions end via the recordings cron",
      "You can manually add or edit sessions if needed",
    ],
  },
  {
    title: "Bookings",
    icon: Calendar,
    href: "/admin/bookings",
    description:
      "View all user bookings for sessions. Shows who booked which session, their status (CONFIRMED, CANCELLED, ATTENDED), and attendance tracking.",
    tips: [
      "Bookings are created when users join a session from their dashboard",
      "The attendance status helps track user engagement",
      "Filter by date to see today's or upcoming bookings",
    ],
  },
  {
    title: "Subscriptions",
    icon: RefreshCw,
    href: "/admin/subscriptions",
    description:
      "Monitor Razorpay subscription statuses. Shows active, paused, and cancelled subscriptions with their billing cycles and amounts.",
    tips: [
      "Subscriptions are managed by Razorpay — status updates come via webhooks",
      "An active subscription means the user has a recurring payment plan",
      "Cancellation requests are processed at the end of the billing cycle",
    ],
  },
  {
    title: "Payments",
    icon: CreditCard,
    href: "/admin/payments",
    description:
      "Complete payment history. Every Razorpay transaction is logged here with order ID, amount, status, coupon used, and timestamps.",
    tips: [
      "All amounts are stored in paise (divide by 100 for rupees)",
      "Payment status: PENDING, PAID, FAILED, REFUNDED",
      "Webhook events from Razorpay update payment statuses automatically",
    ],
  },
  {
    title: "Coupons",
    icon: Ticket,
    href: "/admin/coupons",
    description:
      "Create and manage discount coupons. Supports percentage or fixed-amount discounts with optional min order, max discount cap, usage limits, and expiry dates.",
    tips: [
      "Coupon codes are case-insensitive and must be unique",
      "Set max uses to limit how many times a coupon can be redeemed",
      "Deactivate expired coupons rather than deleting them to preserve order history",
      "Users apply coupons during checkout on the pricing page",
    ],
  },
  {
    title: "Affiliate Products",
    icon: ShoppingBag,
    href: "/admin/affiliate-products",
    description:
      "Manage Amazon affiliate product recommendations shown on the user's Tools page. Add gua sha tools, rollers, oils, mats, books, and other practice essentials.",
    tips: [
      "Each product needs a name, slug, image URL, Amazon affiliate link, and display price",
      "Use the 'Featured' flag to highlight top picks — they appear first",
      "Sort order controls the display sequence (lower = earlier)",
      "Practice types (Face Yoga, Pranayama, Bundle) control which tab the product appears under",
      "Click counts track how many users clicked through to Amazon",
      "Amazon Associates disclosure is automatically shown on the Tools page",
    ],
  },
  {
    title: "Messages",
    icon: MessageSquare,
    href: "/admin/messages",
    description:
      "View WhatsApp and other message logs. Shows sent reminders, booking confirmations, and any failed message deliveries.",
    tips: [
      "Session reminders are sent automatically via the cron job",
      "Failed messages are retried by the retry-messages cron",
      "Check here if a user reports not receiving a reminder",
    ],
  },
  {
    title: "Webhooks",
    icon: Webhook,
    href: "/admin/webhooks",
    description:
      "Monitor incoming webhook events from Clerk (auth) and Razorpay (payments). Useful for debugging sign-up or payment issues.",
    tips: [
      "Clerk webhooks sync user data (create, update, delete)",
      "Razorpay webhooks update order and subscription statuses",
      "Check webhook logs when a payment succeeds on Razorpay but doesn't reflect here",
    ],
  },
  {
    title: "Demo Checkout",
    icon: FlaskConical,
    href: "/admin/demo-checkout",
    description:
      "Test the Razorpay checkout flow without real payments. Use this to verify that the pricing page, coupon application, and payment redirect work correctly.",
    tips: [
      "Use Razorpay test credentials (card: 4111 1111 1111 1111)",
      "Test both one-time and subscription payment flows",
      "Verify that success/failure redirects work properly",
    ],
  },
  {
    title: "Settings",
    icon: Settings,
    href: "/admin/settings",
    description:
      "Configure WhatsApp bot settings, rate limits, and other app-level configurations.",
    tips: [
      "WhatsApp rate limits prevent message flooding",
      "Send a test message to verify WhatsApp connectivity",
    ],
  },
  {
    title: "Super Settings",
    icon: ShieldCheck,
    href: "/admin/super-settings",
    description:
      "Advanced configuration for environment variables, cron job management, and system-level settings. Handle with care.",
    tips: [
      "Review environment variables to ensure all services are configured",
      "Only accessible to ADMIN role users",
      "Changes here can affect the entire application",
    ],
  },
];

const publicPages = [
  { path: "/", name: "Homepage", description: "Landing page with hero, features, and testimonials" },
  { path: "/face-yoga", name: "Face Yoga", description: "Face Yoga product page with plans and pricing" },
  { path: "/pranayama", name: "Pranayama", description: "Pranayama product page with plans and pricing" },
  { path: "/pricing", name: "Pricing", description: "Combined pricing page for all products" },
  { path: "/blog", name: "Blog", description: "Blog listing from Ghost CMS" },
  { path: "/visual-library", name: "Visual Library", description: "Exercise visual reference library" },
  { path: "/coach", name: "Coach Signup", description: "Coach application/onboarding page" },
  { path: "/terms", name: "Terms & Conditions", description: "Legal terms users must accept" },
];

const userPages = [
  { path: "/app", name: "Dashboard", description: "User's home — upcoming sessions, quick actions" },
  { path: "/app/sessions", name: "Sessions", description: "Browse and book upcoming sessions" },
  { path: "/app/progress", name: "Progress", description: "Track practice streaks and history" },
  { path: "/app/recordings", name: "Recordings", description: "Watch past session recordings" },
  { path: "/app/tools", name: "Tools", description: "Curated product recommendations (affiliate)" },
  { path: "/app/billing", name: "Billing", description: "Manage subscription and payment history" },
  { path: "/app/settings", name: "Settings", description: "Update profile, timezone, preferences" },
];

const userFlows = [
  {
    title: "New User Sign-Up Flow",
    steps: [
      "User lands on / (homepage) or /face-yoga or /pranayama",
      "Selects a plan and clicks 'Get Started'",
      "Accepts Terms & Conditions checkbox",
      "Redirected to /auth/sign-up — enters email + password or uses Google",
      "Verifies email with OTP code",
      "Completes profile (first name, last name) on the continue step",
      "Redirected to /onboarding — fills name, phone, timezone, goal",
      "Accepts T&C (if not already accepted)",
      "Redirected to /app dashboard — user is fully onboarded",
    ],
  },
  {
    title: "Returning User Sign-In",
    steps: [
      "User visits /auth/sign-in",
      "Enters email → chooses password or email OTP",
      "Redirected to /app dashboard",
    ],
  },
  {
    title: "Purchase / Subscription Flow",
    steps: [
      "User selects a plan on /face-yoga, /pranayama, or /pricing",
      "Optionally applies a coupon code",
      "Razorpay checkout opens (card, UPI, netbanking)",
      "On success → /checkout/success → membership activated",
      "On failure → /checkout/failed → retry option",
    ],
  },
  {
    title: "Session Booking Flow",
    steps: [
      "User goes to /app/sessions",
      "Sees upcoming sessions for their membership type",
      "Clicks 'Join' to book a session",
      "Gets WhatsApp reminder before session",
      "Joins via Google Meet link",
      "After session, recording becomes available in /app/recordings",
    ],
  },
];

export default function AdminGuidePage() {
  return (
    <div className="max-w-4xl">
      <header className="mb-10">
        <h1 className="text-3xl font-light mb-2">Admin Guide</h1>
        <p className="text-muted-foreground">
          Complete reference for managing Mukha Mudra. Each section below
          explains what it does, where to find it, and tips for daily operations.
        </p>
      </header>

      {/* ── User Flows ── */}
      <section className="mb-12">
        <h2 className="text-xl font-medium mb-4 flex items-center gap-2">
          <Smartphone className="h-5 w-5" />
          User Flows
        </h2>
        <p className="text-sm text-muted-foreground mb-6">
          How users move through the app — from sign-up to booking a session.
        </p>

        <div className="space-y-6">
          {userFlows.map((flow) => (
            <Card key={flow.title} glass>
              <CardHeader className="pb-3">
                <CardTitle className="text-base">{flow.title}</CardTitle>
              </CardHeader>
              <CardContent>
                <ol className="space-y-2">
                  {flow.steps.map((step, i) => (
                    <li key={i} className="flex gap-3 text-sm">
                      <span className="flex-shrink-0 w-6 h-6 rounded-full bg-muted flex items-center justify-center text-xs font-medium">
                        {i + 1}
                      </span>
                      <span className="text-muted-foreground pt-0.5">{step}</span>
                    </li>
                  ))}
                </ol>
              </CardContent>
            </Card>
          ))}
        </div>
      </section>

      {/* ── Public Pages ── */}
      <section className="mb-12">
        <h2 className="text-xl font-medium mb-4 flex items-center gap-2">
          <Globe className="h-5 w-5" />
          Public Pages
        </h2>
        <p className="text-sm text-muted-foreground mb-4">
          Pages visible to everyone, no login required.
        </p>
        <Card glass>
          <CardContent className="p-0">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-border">
                  <th className="text-left p-3 font-medium">Page</th>
                  <th className="text-left p-3 font-medium">Path</th>
                  <th className="text-left p-3 font-medium">Description</th>
                </tr>
              </thead>
              <tbody>
                {publicPages.map((page) => (
                  <tr key={page.path} className="border-b border-border/50">
                    <td className="p-3 font-medium">{page.name}</td>
                    <td className="p-3">
                      <code className="text-xs bg-muted px-1.5 py-0.5 rounded">
                        {page.path}
                      </code>
                    </td>
                    <td className="p-3 text-muted-foreground">{page.description}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </CardContent>
        </Card>
      </section>

      {/* ── User App Pages ── */}
      <section className="mb-12">
        <h2 className="text-xl font-medium mb-4 flex items-center gap-2">
          <CheckCircle2 className="h-5 w-5" />
          User App Pages
        </h2>
        <p className="text-sm text-muted-foreground mb-4">
          Pages visible to logged-in users with an active membership.
        </p>
        <Card glass>
          <CardContent className="p-0">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-border">
                  <th className="text-left p-3 font-medium">Page</th>
                  <th className="text-left p-3 font-medium">Path</th>
                  <th className="text-left p-3 font-medium">Description</th>
                </tr>
              </thead>
              <tbody>
                {userPages.map((page) => (
                  <tr key={page.path} className="border-b border-border/50">
                    <td className="p-3 font-medium">{page.name}</td>
                    <td className="p-3">
                      <code className="text-xs bg-muted px-1.5 py-0.5 rounded">
                        {page.path}
                      </code>
                    </td>
                    <td className="p-3 text-muted-foreground">{page.description}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </CardContent>
        </Card>
      </section>

      {/* ── Admin Sections ── */}
      <section className="mb-12">
        <h2 className="text-xl font-medium mb-4 flex items-center gap-2">
          <ShieldCheck className="h-5 w-5" />
          Admin Panel Reference
        </h2>
        <p className="text-sm text-muted-foreground mb-6">
          Detailed guide for every section of the admin panel.
        </p>

        <div className="space-y-6">
          {sections.map((section) => {
            const Icon = section.icon;
            return (
              <Card key={section.title} glass id={section.title.toLowerCase().replace(/\s+/g, "-")}>
                <CardHeader className="pb-3">
                  <CardTitle className="flex items-center gap-2 text-base">
                    <Icon className="h-4 w-4" />
                    {section.title}
                    <a
                      href={section.href}
                      className="ml-auto text-xs text-muted-foreground hover:text-primary flex items-center gap-1"
                    >
                      Open <ExternalLink className="h-3 w-3" />
                    </a>
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  <p className="text-sm text-muted-foreground">
                    {section.description}
                  </p>
                  {section.tips.length > 0 && (
                    <div>
                      <p className="text-xs font-medium uppercase tracking-wider text-muted-foreground mb-2">
                        Tips
                      </p>
                      <ul className="space-y-1.5">
                        {section.tips.map((tip, i) => (
                          <li
                            key={i}
                            className="text-sm text-muted-foreground flex gap-2"
                          >
                            <span className="text-primary mt-0.5">&#x2022;</span>
                            {tip}
                          </li>
                        ))}
                      </ul>
                    </div>
                  )}
                </CardContent>
              </Card>
            );
          })}
        </div>
      </section>

      {/* ── Cron Jobs ── */}
      <section className="mb-12">
        <h2 className="text-xl font-medium mb-4 flex items-center gap-2">
          <RefreshCw className="h-5 w-5" />
          Background Jobs (Cron)
        </h2>
        <p className="text-sm text-muted-foreground mb-4">
          Automated tasks that run on a schedule. These are Vercel cron jobs
          defined in <code className="text-xs bg-muted px-1.5 py-0.5 rounded">vercel.json</code>.
        </p>
        <Card glass>
          <CardContent className="p-0">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-border">
                  <th className="text-left p-3 font-medium">Job</th>
                  <th className="text-left p-3 font-medium">What it does</th>
                </tr>
              </thead>
              <tbody>
                {[
                  {
                    name: "generate-sessions",
                    desc: "Creates upcoming sessions from active batch schedules",
                  },
                  {
                    name: "fetch-recordings",
                    desc: "Downloads and links session recordings after classes end",
                  },
                  {
                    name: "expire-recording-access",
                    desc: "Removes recording access after expiry period",
                  },
                  {
                    name: "session-reminders",
                    desc: "Sends WhatsApp reminders to users before their booked sessions",
                  },
                  {
                    name: "send-emails",
                    desc: "Processes queued email notifications",
                  },
                  {
                    name: "retry-messages",
                    desc: "Retries failed WhatsApp/email messages",
                  },
                ].map((job) => (
                  <tr key={job.name} className="border-b border-border/50">
                    <td className="p-3">
                      <code className="text-xs bg-muted px-1.5 py-0.5 rounded">
                        {job.name}
                      </code>
                    </td>
                    <td className="p-3 text-muted-foreground">{job.desc}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </CardContent>
        </Card>
      </section>

      {/* ── Quick Reference ── */}
      <section className="mb-12">
        <h2 className="text-xl font-medium mb-4">Quick Reference</h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <Card glass>
            <CardContent className="p-4">
              <h3 className="font-medium mb-2">Razorpay Test Card</h3>
              <p className="text-sm text-muted-foreground">
                Card: <code className="bg-muted px-1 rounded">4111 1111 1111 1111</code>
                <br />
                Expiry: Any future date
                <br />
                CVV: Any 3 digits
                <br />
                OTP: Not required in test mode
              </p>
            </CardContent>
          </Card>
          <Card glass>
            <CardContent className="p-4">
              <h3 className="font-medium mb-2">Key URLs</h3>
              <p className="text-sm text-muted-foreground">
                Production: <code className="bg-muted px-1 rounded">mukhamudra.com</code>
                <br />
                Clerk Dashboard: <code className="bg-muted px-1 rounded">dashboard.clerk.com</code>
                <br />
                Razorpay Dashboard: <code className="bg-muted px-1 rounded">dashboard.razorpay.com</code>
                <br />
                Vercel: <code className="bg-muted px-1 rounded">vercel.com/dashboard</code>
              </p>
            </CardContent>
          </Card>
          <Card glass>
            <CardContent className="p-4">
              <h3 className="font-medium mb-2">User Roles</h3>
              <p className="text-sm text-muted-foreground">
                <strong>USER</strong> — Default role, can book sessions and view content
                <br />
                <strong>COACH</strong> — Can be assigned to batches/sessions
                <br />
                <strong>ADMIN</strong> — Full access to admin panel
              </p>
            </CardContent>
          </Card>
          <Card glass>
            <CardContent className="p-4">
              <h3 className="font-medium mb-2">Payment Statuses</h3>
              <p className="text-sm text-muted-foreground">
                <strong>PENDING</strong> — Checkout initiated, awaiting payment
                <br />
                <strong>PAID</strong> — Successfully paid
                <br />
                <strong>FAILED</strong> — Payment failed or timed out
                <br />
                <strong>REFUNDED</strong> — Payment was refunded
              </p>
            </CardContent>
          </Card>
        </div>
      </section>
    </div>
  );
}
